import type { Story } from '../../types/domain';

// Generated by scripts/extract-stories.mjs. Do not edit by hand.
export const foxAndGrapes: Story = {
  id: 'fox-and-grapes',
  title: 'The Fox and the Grapes',
  author: 'Aesop',
  category: 'fable',
  summary: 'A fox who cannot reach some grapes decides they were sour anyway.',
  paragraphs: [
    'A FAMISHED FOX saw some clusters of ripe black grapes hanging from a trellised vine. She resorted to all her tricks to get at them, but wearied herself in vain, for she could not reach them. At last she turned away, hiding her disappointment and saying: “The Grapes are sour, and not ripe as I thought.”',
  ],
  wordCount: 56,
  readingMinutes: 1,
  source: {
    collection: "Three Hundred Aesop's Fables",
    url: 'https://www.gutenberg.org/ebooks/21',
    translator: 'George Fyler Townsend',
  },
};
