import type { Story } from '../../types/domain';

// Generated by scripts/extract-stories.mjs. Do not edit by hand.
export const hareAndTortoise: Story = {
  id: 'hare-and-tortoise',
  title: 'The Hare and the Tortoise',
  author: 'Aesop',
  category: 'fable',
  summary:
    'A boastful hare naps during a race against a slow and steady tortoise.',
  paragraphs: [
    'A HARE one day ridiculed the short feet and slow pace of the Tortoise, who replied, laughing: “Though you be swift as the wind, I will beat you in a race.” The Hare, believing her assertion to be simply impossible, assented to the proposal; and they agreed that the Fox should choose the course and fix the goal. On the day appointed for the race the two started together. The Tortoise never for a moment stopped, but went on with a slow but steady pace straight to the end of the course. The Hare, lying down by the wayside, fell fast asleep. At last waking up, and moving as fast as he could, he saw the Tortoise had reached the goal, and was comfortably dozing after her fatigue.',
    'Slow but steady wins the race.',
  ],
  wordCount: 134,
  readingMinutes: 1,
  source: {
    collection: "Three Hundred Aesop's Fables",
    url: 'https://www.gutenberg.org/ebooks/21',
    translator: 'George Fyler Townsend',
  },
};
