import type { Story } from '../../types/domain';
import { hanselAndGretel } from './hansel-and-gretel';
import { littleRedCap } from './little-red-cap';
import { rumpelstiltskin } from './rumpelstiltskin';
import { snowdrop } from './snowdrop';
import { ashputtel } from './ashputtel';
import { briarRose } from './briar-rose';
import { emperorsNewClothes } from './emperors-new-clothes';
import { realPrincess } from './real-princess';
import { littleMatchGirl } from './little-match-girl';
import { firTree } from './fir-tree';
import { snowQueen } from './snow-queen';
import { hareAndTortoise } from './hare-and-tortoise';
import { lionAndMouse } from './lion-and-mouse';
import { foxAndGrapes } from './fox-and-grapes';
import { shepherdsBoyAndWolf } from './shepherds-boy-and-wolf';

// Generated by scripts/extract-stories.mjs. Do not edit by hand.
export const STORIES: readonly Story[] = [
  hanselAndGretel,
  littleRedCap,
  rumpelstiltskin,
  snowdrop,
  ashputtel,
  briarRose,
  emperorsNewClothes,
  realPrincess,
  littleMatchGirl,
  firTree,
  snowQueen,
  hareAndTortoise,
  lionAndMouse,
  foxAndGrapes,
  shepherdsBoyAndWolf,
];
