import type { Story } from '../../types/domain';

// Generated by scripts/extract-stories.mjs. Do not edit by hand.
export const lionAndMouse: Story = {
  id: 'lion-and-mouse',
  title: 'The Lion and the Mouse',
  author: 'Aesop',
  category: 'fable',
  summary: 'A lion spares a tiny mouse and is later rescued by it.',
  paragraphs: [
    'A LION was awakened from sleep by a Mouse running over his face. Rising up angrily, he caught him and was about to kill him, when the Mouse piteously entreated, saying: “If you would only spare my life, I would be sure to repay your kindness.” The Lion laughed and let him go. It happened shortly after this that the Lion was caught by some hunters, who bound him by strong ropes to the ground. The Mouse, recognizing his roar, came and gnawed the rope with his teeth, and set him free, exclaiming:',
    '“You ridiculed the idea of my ever being able to help you, not expecting to receive from me any repayment of your favour; now you know that it is possible for even a Mouse to confer benefits on a Lion.”',
  ],
  wordCount: 133,
  readingMinutes: 1,
  source: {
    collection: "Three Hundred Aesop's Fables",
    url: 'https://www.gutenberg.org/ebooks/21',
    translator: 'George Fyler Townsend',
  },
};
